### ISSUE TITLE
사소한 스펠링 오류

### ISSUE THREAD

**Issue by jbkim** [codezoo-ltd/TYPE1SC#2]
/manual/LTE-CATM1_내장형모뎀_xxxxxxx_핸즈온.pdf 
핸즈온 문서 3종에서 IMEI의 약자중 international의 스펠링이 틀림.

_IMEI : Internaitional Mobile Equipment Identity 모뎀의 고유값(phone's fingerprint)을 가져 옵니다._

PDF문서라서 수정이 안되어 메시지 남깁니다. 
그리고 보드 사양서의 핀사양 설명에서는 실제 보드의 실크이름을 기준으로 설명이 되면 더 좋을 것 같습니다. ;)

**Comment by codezoo-ltd** [comment]
수정 했습니다. 의견 감사 합니다!!
