### ISSUE TITLE
주석 스펠링 오류

### ISSUE THREAD

**Issue by genesis0409** [codezoo-ltd/TYPE1SC#3]
examples/ESP32_IoT/TYPE1SC_HTTP_test/TYPE1SC_HTTP_test.ino

line 68: /* Network Regsistraiton Check */

Regsistraiton -> Registration 수정 요청드려요

네트워크 관련 예제에 빠짐없이 포함되어있을듯해요

**Comment by codezoo-ltd** [comment]
수정 했습니다. 의견 감사합니다. ^^

**Comment by codezoo-ltd** [comment]
변경한 내용 git에 반영 했습니다.
